### PR TITLE
Handle short reads and reader failures differently

### LINKED ISSUE #36: panic: runtime error: index out of range
Hi! I've encountered a strange error in backup recovery tool WAL-G using Zstd compression.
Here's a call stack. Who do you think, can this be caused by corrupted data on WAL-G side or is it a problem in Zstd bindings?
Here https://github.com/DataDog/zstd/blob/1.x/zstd_stream.go#L240 code does not check that ```src``` has at least one byte.

### What version of Go are you using (`go version`)?
1.10

### What operating system and processor architecture are you using (`go env`)?
Linux 86_64

### What did you do?

wal-g backup-fetch of 11Tb database

### What did you see instead?

```
panic: runtime error: index out of range

goroutine 4949956 [running]:
github.com/x4m/wal-g/vendor/github.com/DataDog/zstd.(*reader).Read(0xc460b9c360, 0xc43aa28000, 0x1400000, 0x1400000, 0x1400000, 0x0, 0x0)
        /home/robot-gerrit/workspace/wal-g-build-deb/src/github.com/x4m/wal-g/obj-x86_64-linux-gnu/src/github.com/x4m/wal-g/vendor/github.com/DataDog/zstd/zstd_stream.go:240 +0x924
github.com/x4m/wal-g.fastCopy(0xf123a0, 0xc44de66c80, 0x7f5e745d9198, 0xc460b9c360, 0xc460b9c360, 0xc4464e5e60, 0xc420c3bf28)
        /home/robot-gerrit/workspace/wal-g-build-deb/src/github.com/x4m/wal-g/obj-x86_64-linux-gnu/src/github.com/x4m/wal-g/
```

### PR DESCRIPTION
**Pull request by x4m**
I expect this should fix #36 .
In case of network failures in [WAL-G](https:://github.com/wal-g/wal-g) Reader may return ErrUnexpectedEOF and this error could possibly be mistakenly ignored, leading to panic.

### CODE REVIEW

**Comment by Viq111** [comment]
Hi @x4m thanks for your contribution!
I was out the last 2 weeks so I wasn't able to review but will do it in the following days 👀 (wanna update to Go 1.11 too), just wanted to let you know!

File: zstd_stream.go [hunk 1]
```diff
@@ -267,3 +268,24 @@ func (r *reader) Read(p []byte) (int, error) {
...
+	}
+	if n == len(buf) && err == io.EOF {
+		err = nil // EOF at the end is somewhat expected
+	} else if err == io.EOF {
+		err = ErrShortRead
+	}
+	return
+}
+
+var ErrShortRead = errors.New("short read")
```
Comment (Viq111) [inline zstd_stream.go]: nit: can we put this at the beginning or the file.
Also since this error will not be returned (the `if` check if it's a shortRead and shallow), can we make it private ? `ErrShortRead` -> `errShortRead`

**Review by Viq111 — COMMENTED** [review]
Sorry for the delay, PR looks good to me!

I made one small comment (to not blob the public interface), as soon as it's changed, we can merge.

**Comment by x4m** [comment]
@Viq111 thanks for the review!
I've made requested changes. Ping me if there are some other points to improve

**Review by Viq111 — APPROVED** [review]
Nope PR looks good to me
Thanks for contributing!

Closes #36

**Comment by x4m** [comment]
Cool, thanks!
